#!/bin/sh

# Find resources in use
#
#find ~/spoejs/htdocs -type f -exec egrep '<&\|/l&>.*?</&>' {} \; | perl -n -e '@a=m!<&\|/l&>(.*?)</&>!;print map{"$_\n"}@a' | sort | uniq > /tmp/.$$.inuse
find ../htdocs -type f -exec egrep '\*\*.*?\*\*' {} \; | perl -n -e '@a=m!\*\*(.*?)\*\*!;print map{"$_\n"}@a' | sort | uniq > /tmp/.$$.inuse

# Find resources available
#
#cat ~/spoejs/lib/resource.txt  | perl -n -e 'm/<(\w+)>/ and $1=~/(...+)/ and print "$1\n"' > /tmp/.$$.avail
cat ../lib/resource.txt  | perl -n -e 'm/<(\w+)>|^(\w):/ and $1=~/(...+)/ and print "$1\n"' > /tmp/.$$.avail

echo "Keywords in use                         Keywords available"
echo "---------------                         ------------------"
diff --side-by-side -W 72 /tmp/.$$.inuse /tmp/.$$.avail
rm /tmp/.$$.*

