#!/bin/sh

# Find resources in use
#
# Soren's recipe
#find ../htdocs -type f -exec egrep '\*\*.*?\*\*' {} \; | egrep -v '^%#' | perl -n -e '@a=m!\*\*(.*?)\*\*!g;print map{"$_\n"}@a' | sort | uniq > /tmp/.$$.inuse
# Snicki's recipe
find ../htdocs \! -path '*users*' -type f -exec egrep '\*\*.*?\*\*' {} \; | perl -n -e '@a=m!\*\*(.*?)\*\*!g;print map{"$_\n"}@a' | sort | uniq > /tmp/.$$.inuse

# Find resources available
#
cat ../lib/resource.txt | perl -n -e 'm/^(\w+):/ and $1=~/(...+)/ and print "$1\n"' > /tmp/.$$.avail

echo "Keywords in use                         Keywords available"
echo "---------------                         ------------------"
diff --side-by-side -W 72 /tmp/.$$.inuse /tmp/.$$.avail
rm /tmp/.$$.*
