%# Show a list of media with links to larger versions
%#
%# License: Artistic License
%#          http://www.opensource.org/licenses/artistic-license.php
%#
%# $Id: album.sub,v 1.3 2004/04/10 07:54:57 snicki Exp $
%#
<& $w,
   img_list  => \@ml
   img_count => $spoejs{p}{s}
&>
<%init>
  my @ml = $media_list->list( start => $spoejs{p}{s}, count => $count );
</%init>
<%args>
  $w          => undef
  $start      => undef
  $count      => undef
  $media_list => undef
</%args>