<& $w,
  stories  => \@stories,
  navi_opt => \%navi_opt
&>
<%init>
  # XXX: Make ChannelConf or user selectable

my $count = 5;
my $start = $spoejs{p}{s} || 0;
my %sl_opt = ( category  => $spoejs{p}{c},
	       prev      => $count,
	       story_num => $start
	     );

my @stories = $spoejs{SL}->list_stories( %sl_opt );

my %navi_opt = ( url => "/$spoejs{channel}/index.html",
		 count => $count, start => $start, list_ref => $spoejs{SL} );
</%init>
<%args>
  $w => undef
</%args>